# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
    - getting-started/kubernetes/infrastructure

stages: 
- stage: PrepareAgent
  jobs:
    - job: InstallTerraform
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.14.5'
      - script: terraform version
    - job: Init
      steps:
      - task: TerraformTaskV1@0
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'getting-started/kubernetes/infrastructure'
          backendAzureRmResourceGroupName: '$(resourceGroup)'
          backendAzureRmStorageAccountName: '$(storageAccount)'
          backendAzureRmContainerName: '$(containerName)'
          backendAzureRmKey: '$(stateFileName)'

- stage: Validate
  jobs:
    - job: 
pool:
  vmImage: ubuntu-latest

