# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
    - getting-started/kubernetes/infrastructure

stages: 
- stage: PrepeareInfrastructure
  jobs:
  - job: CreateResourceGroup
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $rg = az group list --query "[?name=='${{ variables.resourceGroup }}']" | ConvertFrom-Json
          if ($rg.Length -eq 0){
              Write-Output "Creating resource group ${{ variables.resourceGroup }}"
              az group create --name ${{ variables.resourceGroup }} --location ${{ variables.location }}
          }
  - job: CreateStorageAccount
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $storage = az storage account list --query "[?name=='${{ variables.storageAccount }}']" | ConvertFrom-Json
          if ($storage.Length -eq 0){
              Write-Output "Creating storage account ${{ variables.storageAccount }}"
              az storage account create --name ${{ variables.storageAccount }} --resource-group ${{ variables.resourceGroup }} --location ${{ variables.location }} --sku 'Standard_LRS'
          }
  - job: CreateContainer
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $accountKey=$(az storage account keys list --resource-group ${{ variables.resourceGroup }} --account-name ${{ variables.storageAccount }} --query [0].value -o tsv)
          
          ${{ variables.container }} = az storage container list --account-name ${{ variables.storageAccount }} --account-key $accountKey --query "[?name=='${{ variables.container }}']" | ConvertFrom-Json
          if (${{ variables.container }}.Length -eq 0)
          {
              Write-Output "Creating container ${{ variables.container }}"
              az storage container create --name ${{ variables.container }} --account-name ${{ variables.storageAccount }} --account-key $accountKey
          }
- stage: PrepeareAgent
  jobs:
    - job: InstallTerraform
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.14.5'
      - script: terraform version
    - job: Init
      steps:
      - task: TerraformTaskV1@0
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'getting-started/kubernetes/infrastructure'
          backendAzureRmResourceGroupName: '${{ variables.resourceGroup }}'
          backendAzureRmStorageAccountName: '${{ variables.storageAccount }}'
          backendAzureRmContainerName: '${{ variables.container }}'
          backendAzureRmKey: '${{ variables.stateFileName }}'

pool:
  vmImage: ubuntu-latest

