# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    exclude:
      - master
  paths:
    include:
    - getting-started/kubernetes/infrastructure

variables:
- group: Infrastructure

stages: 
- stage: PrepeareInfrastructure
  jobs:
  - job: CreateStorageAccount
    steps:
    - task: AzureCLI@2
      displayName: "Create resource group"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $rg = az group list --query "[?name=='$env:RESOURCEGROUP']" | ConvertFrom-Json
          if ($rg.Length -eq 0){
              Write-Output "Creating resource group $env:RESOURCEGROUP"
              az group create --name $env:RESOURCEGROUP --location $env:LOCATION
          }
    - task: AzureCLI@2
      displayName: "Create storage account"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $storage = az storage account list --query "[?name=='$env:STORAGEACCOUNT']" | ConvertFrom-Json
          if ($storage.Length -eq 0){
              Write-Output "Creating storage account $env:STORAGEACCOUNT"
              az storage account create --name $env:STORAGEACCOUNT --resource-group $env:RESOURCEGROUP --location $env:LOCATION --sku 'Standard_LRS'
          }
    - task: AzureCLI@2
      displayName: "Create container"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $accountKey=$(az storage account keys list --resource-group $env:RESOURCEGROUP --account-name $env:STORAGEACCOUNT --query [0].value -o tsv)
          
           $container = az storage container list --account-name $env:STORAGEACCOUNT --account-key $accountKey --query "[?name=='$env:CONTAINERNAME']" | ConvertFrom-Json
          if ( $container.Length -eq 0)
          {
              Write-Output "Creating container  $env:CONTAINERNAME"
              az storage container create --name $env:CONTAINERNAME --account-name $env:STORAGEACCOUNT --account-key $accountKey
          }
- stage: PrepeareAgent
  jobs:
    - job: InstallTerraform
      steps:
      - task: TerraformInstaller@0
        inputs:
          terraformVersion: '0.14.5'
      - script: terraform version
    - job: Init
      steps:
      - task: TerraformTaskV1@0
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: 'getting-started/kubernetes/infrastructure'
          backendAzureRmResourceGroupName: $(ResourceGroup)
          backendAzureRmStorageAccountName: $(StorageAccount)
          backendAzureRmContainerName: $(ContainerName)
          backendAzureRmKey: $(StateFileName)

pool:
  vmImage: ubuntu-latest

