trigger:
  - main
  - feature/*
  - release/*

resources:
- repo: self

variables:
  - group: Infrastructure
  - name: version
    value: '$(Build.BuildId)'
  - name: vmImageName
    value: 'windows-2019'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      displayName: "Build and push"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az configure --defaults acr=$env:ACRNAME
          az acr login
          docker-compose -f .\docker-compose.xm1.yml -f .\docker-compose.xm1.override.yml build -e REGISTRY=$($env:ACRNAME).azurecr.io -e VERSION=$(VERSION)