trigger:
  - main
  - feature/*
  - release/*

resources:
- repo: self

variables:
  - group: Infrastructure
  - name: version
    value: '$(Build.BuildId)'
  - name: vmImageName
    value: 'windows-2019'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      displayName: "Az login, set ACR"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az configure --defaults acr=$env:ACRNAME
          az acr login
    - task: PowerShell@2
      displayName: "Prepeare .env file"
      inputs:
        targetType: 'inline'
        script: |
          (Get-Content .env) -replace "^REGISTRY=.*$","REGISTRY=$env:ACRNAME.azurecr.io/docker-examples/" | Set-Content .env
          (Get-Content .env) -replace "^VERSION=.*$","VERSION=$(VERSION)" | Set-Content .env
        workingDirectory: 'custom-images'
    - task: PowerShell@2
      displayName: "Run Docker Comopose build"
      inputs:
        targetType: 'inline'
        script: 'docker-compose -f .\docker-compose.xm1.yml -f .\docker-compose.xm1.override.yml build'
        workingDirectory: 'custom-images'
    - task: PowerShell@2
      displayName: "Push images"
      inputs:
        targetType: 'inline'
        script: 'docker-compose -f .\docker-compose.xm1.yml -f .\docker-compose.xm1.override.yml push'
        workingDirectory: 'custom-images'
