trigger:
  - none

resources:
- repo: self

variables:
  - group: docker-examples-variables

jobs: 
  - job: PrepeareAgent
    steps:
    - task: AzureCLI@2
      displayName: "Get AKS Credentials"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks get-credentials --name $env:AKSNAME --resource-group $env:RESOURCEGROUPNAME --admin'
    - task: Bash@3
      displayName: 'Update kustomize'
      inputs:
        targetType: 'inline'
        script: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash -s /usr/local/bin
          kustomize version
  - job: DeployExternal
    dependsOn: PrepeareAgent
    steps:
    - task: AzureCLI@2
      displayName: "Deploy External services"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'kustomize build --load_restrictor none external/external-nosql | kubectl apply -f -'
        workingDirectory: getting-started/kubernetes/application/xp1/external
pool:
  vmImage: ubuntu-latest