trigger:
  - none

resources:
- repo: self

variables:
  - group: docker-examples-variables

jobs: 
  - job: Initialize
    steps:
    - task: AzureCLI@2
      displayName: "Get AKS Credentials"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'pscore'
        scriptLocation: 'inlineScript'
        inlineScript: 'az aks get-credentials --name $env:AKSNAME --resource-group $env:RESOURCEGROUPNAME --admin'
    - task: AzureCLI@2
      displayName: "Deploy Application"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'kustomize build --load-restrictor LoadRestrictionsNone . | kubectl apply -f -'
        workingDirectory: getting-started/kubernetes/application/xp1/overlays
    - task: AzureCLI@2
      displayName: "Configure ingress"
      inputs:
        azureSubscription: 'DockerExamplesAzureConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'kustomize build --load-restrictor LoadRestrictionsNone ingress-nginx | kubectl apply -f -'
        workingDirectory: getting-started/kubernetes/application/xp1/overlays

pool:
  vmImage: ubuntu-latest