trigger:
  - none

resources:
- repo: self

variables:
  - group: docker-examples-variables

stages:
- stage: PrepeareAgent
  jobs:
    - job: Configure
      steps:
      - task: CmdLine@2
        displayName: "Install Kustomize"
        inputs:
          script: |
            sudo apt-get update
            sudo apt-get install kustomize
      - task: AzureCLI@2
        displayName: "Configure kubectl"
        inputs:
          azureSubscription: 'DockerExamplesAzureConnection'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          inlineScript: 'az aks get-credentials --name $(AKSName) --resource-group $(ResourceGroup) --admin'

# - stage: Deploy
#   displayName: Deploy XM1

pool:
  vmImage: ubuntu-latest